using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarFleetPro.API.Migrations
{
    /// <inheritdoc />
    public partial class AddRBACAndNewTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Branch kolonu önceki migration'da eklendi — IF NOT EXISTS ile güvenli ekle
            migrationBuilder.Sql(@"ALTER TABLE ""Vehicles"" ADD COLUMN IF NOT EXISTS ""Branch"" text NOT NULL DEFAULT '';");
            migrationBuilder.Sql(@"ALTER TABLE ""Vehicles"" ADD COLUMN IF NOT EXISTS ""Color"" text;");

            // Maintenances tablosuna yeni kolonlar
            migrationBuilder.Sql(@"ALTER TABLE ""Maintenances"" ADD COLUMN IF NOT EXISTS ""MaintenanceType"" integer NOT NULL DEFAULT 0;");
            migrationBuilder.Sql(@"ALTER TABLE ""Maintenances"" ADD COLUMN IF NOT EXISTS ""NextInspectionDate"" timestamp with time zone;");

            // EndDate'i nullable yap (varsa)
            migrationBuilder.Sql(@"ALTER TABLE ""Maintenances"" ALTER COLUMN ""EndDate"" DROP NOT NULL;");

            // AspNetUsers tablosuna yeni kolonlar
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" ADD COLUMN IF NOT EXISTS ""Department"" text;");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" ADD COLUMN IF NOT EXISTS ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW();");

            // CarBrands tablosu (önceki migration'da oluşturulmuş olabilir)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""CarBrands"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" text NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""CarColors"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" text NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""CarModels"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""BrandId"" integer NOT NULL,
                    ""Name"" text NOT NULL
                );
            ");

            // DamageRecords tablosu (yeni) — önceki başarısız migration denemesi varsa temizle
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""DamageRecords"";");
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""DamageRecords"" (
                    ""DamageRecordId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""VehicleId"" integer NOT NULL,
                    ""ReportedByUserId"" text,
                    ""DamageType"" integer NOT NULL DEFAULT 0,
                    ""Description"" text NOT NULL DEFAULT '',
                    ""DamageDate"" timestamp with time zone NOT NULL,
                    ""EstimatedCost"" numeric,
                    ""Status"" integer NOT NULL DEFAULT 0,
                    ""PhotoUrl"" text,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT ""FK_DamageRecords_Vehicles_VehicleId"" FOREIGN KEY (""VehicleId"") REFERENCES ""Vehicles"" (""VehicleId"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_DamageRecords_AspNetUsers_ReportedByUserId"" FOREIGN KEY (""ReportedByUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DamageRecords_VehicleId"" ON ""DamageRecords"" (""VehicleId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_DamageRecords_ReportedByUserId"" ON ""DamageRecords"" (""ReportedByUserId"");");

            // Invoices tablosu (yeni)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Invoices"" (
                    ""InvoiceId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""RentalId"" integer NOT NULL,
                    ""Amount"" numeric NOT NULL DEFAULT 0,
                    ""IssuedAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""PaidAt"" timestamp with time zone,
                    ""Status"" integer NOT NULL DEFAULT 0,
                    ""Notes"" text,
                    CONSTRAINT ""FK_Invoices_Rentals_RentalId"" FOREIGN KEY (""RentalId"") REFERENCES ""Rentals"" (""RentalId"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Invoices_RentalId"" ON ""Invoices"" (""RentalId"");");

            // Notifications tablosu (yeni)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Notifications"" (
                    ""NotificationId"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TargetUserId"" text,
                    ""Title"" text NOT NULL DEFAULT '',
                    ""Message"" text NOT NULL DEFAULT '',
                    ""Type"" integer NOT NULL DEFAULT 0,
                    ""IsRead"" boolean NOT NULL DEFAULT false,
                    ""SentAt"" timestamp with time zone NOT NULL DEFAULT NOW(),
                    ""RelatedVehicleId"" integer,
                    ""RelatedRentalId"" integer,
                    CONSTRAINT ""FK_Notifications_AspNetUsers_TargetUserId"" FOREIGN KEY (""TargetUserId"") REFERENCES ""AspNetUsers"" (""Id"") ON DELETE SET NULL
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Notifications_TargetUserId"" ON ""Notifications"" (""TargetUserId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Notifications"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Invoices"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""DamageRecords"";");

            migrationBuilder.Sql(@"ALTER TABLE ""Maintenances"" DROP COLUMN IF EXISTS ""MaintenanceType"";");
            migrationBuilder.Sql(@"ALTER TABLE ""Maintenances"" DROP COLUMN IF EXISTS ""NextInspectionDate"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" DROP COLUMN IF EXISTS ""Department"";");
            migrationBuilder.Sql(@"ALTER TABLE ""AspNetUsers"" DROP COLUMN IF EXISTS ""CreatedAt"";");
        }
    }
}
